### PR TITLE
[#249] Enable QueueProcessor to handle other HTTP methods

### LINKED ISSUE #249: QueueProcessor cannot serve Listener-Hooks for PATCH, HEAD, etc
From client side we can set a Listener-Hook for PATCH, HEAD etc. But later QueueProcessor can't serve it.

Eg if we send a PATCH request, head of queue will be a PATCH message (as expected of course). But badly, QueueProcessor fails to handle that PATCH as he only supports GET, PUT, POST and DELETE

See [QueueProcessor.java:69](https://github.com/swisspush/gateleen/blob/v1.1.33/gateleen-queue/src/main/java/org/swisspush/gateleen/queue/queuing/QueueProcessor.java#L69) calling [ctor of HttpRequest](https://github.com/swisspush/gateleen/blob/v1.1.33/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L54) which then only accept whitelisted methods listed in [switch at HttpRequest.java:60](https://github.com/swisspush/gateleen/blob/v1.1.33/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L60-L68).

Finally, the queue is blocked with error message like:

    ERROR QueueProcessor - Could not build request: {"queue":"listener-hook-http+reproducer+tmp","payload":"{\"method\":\"PATCH\",\"uri\":\"/my-web-ctxt/server/hooks/v1/listeners/http/foo/bar\",\"headers\":[  /*Headers skipped here*/  ],\"payload\":\"\",\"queueTimestamp\":1234567897750}"} error is Request method must be one of GET, PUT, POST or DELETE

Even the two expiries (x-expire-after and x-queue-expire-after, skipped in example log) don't work as they depend of a successful decoded payload to a HttpMessage object.

### PR DESCRIPTION
**Pull request by hiddenalpha**
- Accept only whitelisted HTTP methods on listener registration which
  namely are: GET, HEAD, PUT, POST, DELETE, OPTIONS and PATCH.
- Respond with a HTTP 400 in case a not whitelisted method got used.
- Document possible exceptions on public API.
- Drop enqueueing requests with non-processable HTTP methods and log
  that attempt.

Fixes #249 .

### CODE REVIEW

File: gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java [hunk 1]
```diff
@@ -50,6 +50,11 @@ public HttpRequest(HttpMethod method, String uri, MultiMap headers, byte[] paylo
 
     /**
      * @param object object
+     * @throws IllegalArgumentException
+     *      When passed in JSON is not in expected format.
+     * @throws ClassCastException
```
Comment (mcweba) [inline gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java]: Does it throw both exceptions now? If not change the javadoc

File: gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java [hunk 2]
```diff
@@ -1061,6 +1062,33 @@ private void handleListenerRegistration(final HttpServerRequest request) {
...
+            hook = new JsonObject(hookData);
+        } catch (DecodeException e) {
+            log.error("Cannot decode JSON", e);
+            badRequest(request, "Cannot decode JSON", e.getMessage());
+            return true;
+        }
+        final JsonArray methods = hook.getJsonArray("methods");
+        for (Object method : methods) {
+            if( !QueueProcessor.httpMethodIsQueueable( HttpMethod.valueOf((String)method) ) ){
+                final String msg = "Listener registration request tries to hook for forbidden '"+method+"' method.";
```
Comment (mcweba) [inline gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java]: I would not use the term "forbidden" in this log message. Better use "not allowed" since forbidden implies that the client has insufficient permissions to make the request which is not true.

File: gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java [hunk 3]
```diff
@@ -1061,6 +1062,33 @@ private void handleListenerRegistration(final HttpServerRequest request) {
...
+                log.error( msg );
+                badRequest(request, "Bad Request", msg+"\n" );
```
Comment (mcweba) [inline gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java]: Do not respond this requests with "400 Bad Request". Use "405 Method not Allowed"

File: gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java (hunk 1 above)
Comment (hiddenalpha) [reply gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java]: There's nothing new with those exceptions. They were already there before my change. I only documented them because that was missing and would help a lot to write more reliable code. Here some links pointing to previous release:

**IllegalArgumentException**:
- Thrown at lines [58](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L58), [67](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L67) and [73](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L73).

**ClassCastException**:
- Thrown at lines [55](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L55), [56](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L56), [69](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L69) and [73](https://github.com/swisspush/gateleen/blob/develop/gateleen-core/src/main/java/org/swisspush/gateleen/core/http/HttpRequest.java#L73).

File: gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java (hunk 2 above)
Comment (hiddenalpha) [reply gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java]: Ok. Will do 👍

File: gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java (hunk 3 above)
Comment (mcweba) [reply gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java]: Good point. I did not thought about this. Therefore it's OK to respond with a 400

File: gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java [hunk 4]
```diff
@@ -479,11 +489,11 @@ public void listenerRegistration_rejectNotWhitelistedHttpMethods(TestContext tes
             }
 
             // Trigger
-            hookHandler.handle( request );
+            hookHandler.handle(request);
 
             { // Assert request got rejected.
-                testContext.assertTrue( statusCodePtr[0] >= 400 );
-                testContext.assertTrue( statusCodePtr[0] <= 499 );
+                testContext.assertTrue(statusCodePtr[0] >= 400);
```
Comment (mcweba) [inline gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java]: Why not checking that status code is 400 when requests with these methods are made?

Comment (hiddenalpha) [reply gateleen-hook/src/test/java/org/swisspush/gateleen/hook/HookHandlerTest.java]: Hmm. Yes would be an option of course. Didn't think about that. Will do 👍
